//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MifareOneTool.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MifareOneTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 [0-9A-Fa-f]{32} 的當地語系化字串。
        /// </summary>
        public static string _0_9A_Fa_f_32 {
            get {
                return ResourceManager.GetString("_0_9A_Fa_f_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ##Nonce收集完畢## 的當地語系化字串。
        /// </summary>
        public static string _Nonce收集完毕 {
            get {
                return ResourceManager.GetString("_Nonce收集完毕", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 +Sector:  的當地語系化字串。
        /// </summary>
        public static string _Sector {
            get {
                return ResourceManager.GetString("_Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  區塊不同
        /// 的當地語系化字串。
        /// </summary>
        public static string _个块不同 {
            get {
                return ResourceManager.GetString("_个块不同", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ##已保存- 的當地語系化字串。
        /// </summary>
        public static string _已保存 {
            get {
                return ResourceManager.GetString("_已保存", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ##已自動保存- 的當地語系化字串。
        /// </summary>
        public static string _已自动保存 {
            get {
                return ResourceManager.GetString("_已自动保存", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 #扇區  的當地語系化字串。
        /// </summary>
        public static string _扇区 {
            get {
                return ResourceManager.GetString("_扇区", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ##文件中的值錯誤## 的當地語系化字串。
        /// </summary>
        public static string _文件中的值错误 {
            get {
                return ResourceManager.GetString("_文件中的值错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  有數據 的當地語系化字串。
        /// </summary>
        public static string _有数据 {
            get {
                return ResourceManager.GetString("_有数据", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  有錯誤 的當地語系化字串。
        /// </summary>
        public static string _有错误 {
            get {
                return ResourceManager.GetString("_有错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ##未保存## 的當地語系化字串。
        /// </summary>
        public static string _未保存 {
            get {
                return ResourceManager.GetString("_未保存", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ##程序已被強制停止## 的當地語系化字串。
        /// </summary>
        public static string _程序已被强制停止 {
            get {
                return ResourceManager.GetString("_程序已被强制停止", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  空扇區 的當地語系化字串。
        /// </summary>
        public static string _空扇区 {
            get {
                return ResourceManager.GetString("_空扇区", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ##緩存文件異常## 的當地語系化字串。
        /// </summary>
        public static string _缓存文件异常 {
            get {
                return ResourceManager.GetString("_缓存文件异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ，計算得到BCC= 的當地語系化字串。
        /// </summary>
        public static string _计算得到BCC {
            get {
                return ResourceManager.GetString("_计算得到BCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 #軟體版本  的當地語系化字串。
        /// </summary>
        public static string _软件版本 {
            get {
                return ResourceManager.GetString("_软件版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ##運行出錯## 的當地語系化字串。
        /// </summary>
        public static string _运行出错 {
            get {
                return ResourceManager.GetString("_运行出错", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ##運行完畢## 的當地語系化字串。
        /// </summary>
        public static string _运行完毕 {
            get {
                return ResourceManager.GetString("_运行完毕", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AB文件中一個或兩個無效。 的當地語系化字串。
        /// </summary>
        public static string AB文件中一个或两个无效 {
            get {
                return ResourceManager.GetString("AB文件中一个或两个无效", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ACR122U支持已經打開過。 的當地語系化字串。
        /// </summary>
        public static string ACR122U支持已经打开过 {
            get {
                return ResourceManager.GetString("ACR122U支持已经打开过", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 DUMP文件|*.dump|MFD文件|*.mfd 的當地語系化字串。
        /// </summary>
        public static string DUMP文件_dump_MFD文件_mfd {
            get {
                return ResourceManager.GetString("DUMP文件_dump_MFD文件_mfd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Information 的當地語系化字串。
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 InputError 的當地語系化字串。
        /// </summary>
        public static string InputError {
            get {
                return ResourceManager.GetString("InputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 KeyA/B/N 的當地語系化字串。
        /// </summary>
        public static string KeyA_B_N {
            get {
                return ResourceManager.GetString("KeyA_B_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MCT格式|*.* 的當地語系化字串。
        /// </summary>
        public static string MCT格式 {
            get {
                return ResourceManager.GetString("MCT格式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MFD文件|*.mfd;*.dump 的當地語系化字串。
        /// </summary>
        public static string MFD文件_mfd_dump {
            get {
                return ResourceManager.GetString("MFD文件_mfd_dump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MFD文件|*.mfd|DUMP文件|*.dump 的當地語系化字串。
        /// </summary>
        public static string MFD文件_mfd_DUMP文件_dump {
            get {
                return ResourceManager.GetString("MFD文件_mfd_DUMP文件_dump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MifareOne Tool 的當地語系化字串。
        /// </summary>
        public static string MifareOne_Tool {
            get {
                return ResourceManager.GetString("MifareOne_Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MifareOne Tool - 已取消 的當地語系化字串。
        /// </summary>
        public static string MifareOne_Tool_已取消 {
            get {
                return ResourceManager.GetString("MifareOne_Tool_已取消", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MifareOne Tool - 已终止 的當地語系化字串。
        /// </summary>
        public static string MifareOne_Tool_已终止 {
            get {
                return ResourceManager.GetString("MifareOne_Tool_已终止", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MifareOne Tool - 運行中 的當地語系化字串。
        /// </summary>
        public static string MifareOne_Tool_运行中 {
            get {
                return ResourceManager.GetString("MifareOne_Tool_运行中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MifareOne Tool - 運行完畢 的當地語系化字串。
        /// </summary>
        public static string MifareOne_Tool_运行完毕 {
            get {
                return ResourceManager.GetString("MifareOne_Tool_运行完毕", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 nfc-bin/collect.exe 的當地語系化字串。
        /// </summary>
        public static string nfc_bin_collect_exe {
            get {
                return ResourceManager.GetString("nfc_bin_collect_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap outline_info_black_18pt_1x {
            get {
                object obj = ResourceManager.GetObject("outline_info_black_18pt_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 。 的當地語系化字串。
        /// </summary>
        public static string res {
            get {
                return ResourceManager.GetString("res", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap round_chevron_right_black_24dp {
            get {
                object obj = ResourceManager.GetObject("round_chevron_right_black_24dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap round_clear_black_24dp {
            get {
                object obj = ResourceManager.GetObject("round_clear_black_24dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap round_done_all_black_18pt_1x {
            get {
                object obj = ResourceManager.GetObject("round_done_all_black_18pt_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap round_done_all_black_24dp {
            get {
                object obj = ResourceManager.GetObject("round_done_all_black_24dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap round_done_all_black_24pt_1x {
            get {
                object obj = ResourceManager.GetObject("round_done_all_black_24pt_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap round_done_black_24pt_1x {
            get {
                object obj = ResourceManager.GetObject("round_done_black_24pt_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap round_done_outline_black_24pt_1x {
            get {
                object obj = ResourceManager.GetObject("round_done_outline_black_24pt_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap round_info_black_18pt_1x {
            get {
                object obj = ResourceManager.GetObject("round_info_black_18pt_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap round_sync_black_18pt_1x {
            get {
                object obj = ResourceManager.GetObject("round_sync_black_18pt_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap round_timer_black_18pt_1x {
            get {
                object obj = ResourceManager.GetObject("round_timer_black_18pt_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap round_update_black_18pt_1x {
            get {
                object obj = ResourceManager.GetObject("round_update_black_18pt_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap round_update_black_24pt_1x {
            get {
                object obj = ResourceManager.GetObject("round_update_black_24pt_1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 txt文件|*.txt 的當地語系化字串。
        /// </summary>
        public static string txt文件_txt {
            get {
                return ResourceManager.GetString("txt文件_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UID已改為 的當地語系化字串。
        /// </summary>
        public static string UID已改为 {
            get {
                return ResourceManager.GetString("UID已改为", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不恰當的4字節UID長度 的當地語系化字串。
        /// </summary>
        public static string 不恰当的4字节UID长度 {
            get {
                return ResourceManager.GetString("不恰当的4字节UID长度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用KeyA（是）或KeyB（否）？ 的當地語系化字串。
        /// </summary>
        public static string 使用KeyA_是_或KeyB_否 {
            get {
                return ResourceManager.GetString("使用KeyA_是_或KeyB_否", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用KeyA（是）或KeyB（否），還是不使用（用於全新白卡）（取消）？ 的當地語系化字串。
        /// </summary>
        public static string 使用KeyA_是_或KeyB_否_还是不使用_用于全新白卡_ {
            get {
                return ResourceManager.GetString("使用KeyA_是_或KeyB_否_还是不使用_用于全新白卡_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 俄語 的當地語系化字串。
        /// </summary>
        public static string 俄语 {
            get {
                return ResourceManager.GetString("俄语", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 共找到  的當地語系化字串。
        /// </summary>
        public static string 共找到 {
            get {
                return ResourceManager.GetString("共找到", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 寫入出錯 的當地語系化字串。
        /// </summary>
        public static string 写入出错 {
            get {
                return ResourceManager.GetString("写入出错", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 加載的S50卡文件大小異常。 的當地語系化字串。
        /// </summary>
        public static string 加载的S50卡文件大小异常 {
            get {
                return ResourceManager.GetString("加载的S50卡文件大小异常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 加載的文件不存在。 的當地語系化字串。
        /// </summary>
        public static string 加载的文件不存在 {
            get {
                return ResourceManager.GetString("加载的文件不存在", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 危險操作警告 的當地語系化字串。
        /// </summary>
        public static string 危险操作警告 {
            get {
                return ResourceManager.GetString("危险操作警告", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 同時打開ACR122U支持可能會引起操作速度下降。
        ///請確認是否要繼續操作？ 的當地語系化字串。
        /// </summary>
        public static string 同时打开ACR122U支持可能会引起操作速度下降_请确认是否 {
            get {
                return ResourceManager.GetString("同时打开ACR122U支持可能会引起操作速度下降_请确认是否", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 字典文件|*.dic 的當地語系化字串。
        /// </summary>
        public static string 字典文件_dic {
            get {
                return ResourceManager.GetString("字典文件_dic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密鑰字典文件|*.dic 的當地語系化字串。
        /// </summary>
        public static string 密钥字典文件_dic {
            get {
                return ResourceManager.GetString("密钥字典文件_dic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 將自動選擇首個設備： 的當地語系化字串。
        /// </summary>
        public static string 将自动选择首个设备 {
            get {
                return ResourceManager.GetString("将自动选择首个设备", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 將要寫入的文件存在錯誤，請用高級模式中的Hex工具打開查看。 的當地語系化字串。
        /// </summary>
        public static string 将要写入的文件存在错误_请用高级模式中的Hex工具打开查看 {
            get {
                return ResourceManager.GetString("将要写入的文件存在错误_请用高级模式中的Hex工具打开查看", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已保存到 的當地語系化字串。
        /// </summary>
        public static string 已保存到 {
            get {
                return ResourceManager.GetString("已保存到", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已啟用CUID空卡寫入補丁 的當地語系化字串。
        /// </summary>
        public static string 已启用CUID空卡写入补丁 {
            get {
                return ResourceManager.GetString("已启用CUID空卡写入补丁", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已導出MCT文件 的當地語系化字串。
        /// </summary>
        public static string 已导出MCT文件 {
            get {
                return ResourceManager.GetString("已导出MCT文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已導出密鑰字典文件 的當地語系化字串。
        /// </summary>
        public static string 已导出密钥字典文件 {
            get {
                return ResourceManager.GetString("已导出密钥字典文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已打開。 的當地語系化字串。
        /// </summary>
        public static string 已打开 {
            get {
                return ResourceManager.GetString("已打开", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已找到！K= 的當地語系化字串。
        /// </summary>
        public static string 已找到_K {
            get {
                return ResourceManager.GetString("已找到_K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已指定使用該NFC設備： 的當地語系化字串。
        /// </summary>
        public static string 已指定使用该NFC设备 {
            get {
                return ResourceManager.GetString("已指定使用该NFC设备", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已更新扇區 的當地語系化字串。
        /// </summary>
        public static string 已更新扇区 {
            get {
                return ResourceManager.GetString("已更新扇区", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已重置並新建卡。 的當地語系化字串。
        /// </summary>
        public static string 已重置并新建卡 {
            get {
                return ResourceManager.GetString("已重置并新建卡", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始執行CUID/FUID卡片寫入…… 的當地語系化字串。
        /// </summary>
        public static string 开始执行CUID_FUID卡片写入 {
            get {
                return ResourceManager.GetString("开始执行CUID_FUID卡片写入", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始執行HardNested收集數據…… 的當地語系化字串。
        /// </summary>
        public static string 开始执行HardNested收集数据 {
            get {
                return ResourceManager.GetString("开始执行HardNested收集数据", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始執行HardNested解密強化卡…… 的當地語系化字串。
        /// </summary>
        public static string 开始执行HardNested解密强化卡 {
            get {
                return ResourceManager.GetString("开始执行HardNested解密强化卡", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始執行MFOC解密…… 的當地語系化字串。
        /// </summary>
        public static string 开始执行MFOC解密 {
            get {
                return ResourceManager.GetString("开始执行MFOC解密", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始執行UFUID卡片鎖定…… 的當地語系化字串。
        /// </summary>
        public static string 开始执行UFUID卡片锁定 {
            get {
                return ResourceManager.GetString("开始执行UFUID卡片锁定", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始執行UID卡片全格…… 的當地語系化字串。
        /// </summary>
        public static string 开始执行UID卡片全格 {
            get {
                return ResourceManager.GetString("开始执行UID卡片全格", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始執行UID卡片寫入…… 的當地語系化字串。
        /// </summary>
        public static string 开始执行UID卡片写入 {
            get {
                return ResourceManager.GetString("开始执行UID卡片写入", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始執行UID卡片設定卡號…… 的當地語系化字串。
        /// </summary>
        public static string 开始执行UID卡片设定卡号 {
            get {
                return ResourceManager.GetString("开始执行UID卡片设定卡号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始執行UID卡片讀取…… 的當地語系化字串。
        /// </summary>
        public static string 开始执行UID卡片读取 {
            get {
                return ResourceManager.GetString("开始执行UID卡片读取", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始執行全加密卡片爆破…… 的當地語系化字串。
        /// </summary>
        public static string 开始执行全加密卡片爆破 {
            get {
                return ResourceManager.GetString("开始执行全加密卡片爆破", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始執行寫入M1卡片…… 的當地語系化字串。
        /// </summary>
        public static string 开始执行写入M1卡片 {
            get {
                return ResourceManager.GetString("开始执行写入M1卡片", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始執行字典模式MFOC解密…… 的當地語系化字串。
        /// </summary>
        public static string 开始执行字典模式MFOC解密 {
            get {
                return ResourceManager.GetString("开始执行字典模式MFOC解密", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始執行掃描卡片…… 的當地語系化字串。
        /// </summary>
        public static string 开始执行扫描卡片 {
            get {
                return ResourceManager.GetString("开始执行扫描卡片", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始執行格式化M1卡片…… 的當地語系化字串。
        /// </summary>
        public static string 开始执行格式化M1卡片 {
            get {
                return ResourceManager.GetString("开始执行格式化M1卡片", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始執行檢測卡片加密…… 的當地語系化字串。
        /// </summary>
        public static string 开始执行检测卡片加密 {
            get {
                return ResourceManager.GetString("开始执行检测卡片加密", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始執行檢測設備…… 的當地語系化字串。
        /// </summary>
        public static string 开始执行检测设备 {
            get {
                return ResourceManager.GetString("开始执行检测设备", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始執行讀取卡片…… 的當地語系化字串。
        /// </summary>
        public static string 开始执行读取卡片 {
            get {
                return ResourceManager.GetString("开始执行读取卡片", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始執行重設UID卡片卡號…… 的當地語系化字串。
        /// </summary>
        public static string 开始执行重置UID卡片卡号 {
            get {
                return ResourceManager.GetString("开始执行重置UID卡片卡号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 當前扇區數據仍有錯誤，不能執行修改。 的當地語系化字串。
        /// </summary>
        public static string 当前扇区数据仍有错误_不能执行修改 {
            get {
                return ResourceManager.GetString("当前扇区数据仍有错误_不能执行修改", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 當前選定扇區：？？ 的當地語系化字串。
        /// </summary>
        public static string 当前选定扇区 {
            get {
                return ResourceManager.GetString("当前选定扇区", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 當前選定扇區： 的當地語系化字串。
        /// </summary>
        public static string 当前选定扇区0 {
            get {
                return ResourceManager.GetString("当前选定扇区0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您可以上傳到雲端計算服務節點進行計算。 的當地語系化字串。
        /// </summary>
        public static string 您可以上传到云计算服务节点进行计算 {
            get {
                return ResourceManager.GetString("您可以上传到云计算服务节点进行计算", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您已經運行了MifareOne Tool，打開多個本程式可能會造成衝突及不可預料到的錯誤。
        ///確認要繼續嗎？ 的當地語系化字串。
        /// </summary>
        public static string 您已经运行了MifareOne_Tool_打开多个本程序可能 {
            get {
                return ResourceManager.GetString("您已经运行了MifareOne_Tool_打开多个本程序可能", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您正在試圖重複運行 的當地語系化字串。
        /// </summary>
        public static string 您正在试图重复运行 {
            get {
                return ResourceManager.GetString("您正在试图重复运行", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您沒有給定最後一次寫卡導致0塊損壞的卡數據文件來作為寫卡時的金鑰源。
        ///操作終止。 的當地語系化字串。
        /// </summary>
        public static string 您没有给定最后一次写卡导致0块损坏的卡数据文件来作为写卡时的 {
            get {
                return ResourceManager.GetString("您没有给定最后一次写卡导致0块损坏的卡数据文件来作为写卡时的", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 扇區 的當地語系化字串。
        /// </summary>
        public static string 扇区 {
            get {
                return ResourceManager.GetString("扇区", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 扇區  的當地語系化字串。
        /// </summary>
        public static string 扇区0 {
            get {
                return ResourceManager.GetString("扇区0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 打開了 的當地語系化字串。
        /// </summary>
        public static string 打开了 {
            get {
                return ResourceManager.GetString("打开了", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 打開出錯 的當地語系化字串。
        /// </summary>
        public static string 打开出错 {
            get {
                return ResourceManager.GetString("打开出错", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 提示訊息 的當地語系化字串。
        /// </summary>
        public static string 提示信息 {
            get {
                return ResourceManager.GetString("提示信息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 文件內不是含有64個塊數據，可能不完整或不相容。 的當地語系化字串。
        /// </summary>
        public static string 文件内不是含有64个块数据_可能不完整或不兼容 {
            get {
                return ResourceManager.GetString("文件内不是含有64个块数据_可能不完整或不兼容", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無金鑰 的當地語系化字串。
        /// </summary>
        public static string 无密钥 {
            get {
                return ResourceManager.GetString("无密钥", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法找到MFF08程序文件。
        ///操作終止。 的當地語系化字串。
        /// </summary>
        public static string 无法找到MFF08程序文件_操作终止 {
            get {
                return ResourceManager.GetString("无法找到MFF08程序文件_操作终止", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示扇區 的當地語系化字串。
        /// </summary>
        public static string 显示扇区 {
            get {
                return ResourceManager.GetString("显示扇区", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 有任務運行中，不可執行。 的當地語系化字串。
        /// </summary>
        public static string 有任务运行中_不可执行 {
            get {
                return ResourceManager.GetString("有任务运行中_不可执行", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未知 的當地語系化字串。
        /// </summary>
        public static string 未知 {
            get {
                return ResourceManager.GetString("未知", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未選擇有效key.mfd。 的當地語系化字串。
        /// </summary>
        public static string 未选择有效key_mfd {
            get {
                return ResourceManager.GetString("未选择有效key_mfd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 本地版本  的當地語系化字串。
        /// </summary>
        public static string 本地版本 {
            get {
                return ResourceManager.GetString("本地版本", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 標準 的當地語系化字串。
        /// </summary>
        public static string 标准 {
            get {
                return ResourceManager.GetString("标准", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 正在使用智慧KeyABN… 的當地語系化字串。
        /// </summary>
        public static string 正在使用智能KeyABN {
            get {
                return ResourceManager.GetString("正在使用智能KeyABN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 正在打開ACR122U支持…… 的當地語系化字串。
        /// </summary>
        public static string 正在打开ACR122U支持 {
            get {
                return ResourceManager.GetString("正在打开ACR122U支持", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 正在檢索是否存在key.mfd… 的當地語系化字串。
        /// </summary>
        public static string 正在检索是否存在key_mfd {
            get {
                return ResourceManager.GetString("正在检索是否存在key_mfd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 沒有發現任何有效的NFC設備。 的當地語系化字串。
        /// </summary>
        public static string 没有发现任何有效的NFC设备 {
            get {
                return ResourceManager.GetString("没有发现任何有效的NFC设备", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 秒 的當地語系化字串。
        /// </summary>
        public static string 秒 {
            get {
                return ResourceManager.GetString("秒", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 空閒 的當地語系化字串。
        /// </summary>
        public static string 空闲 {
            get {
                return ResourceManager.GetString("空闲", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 終端內容已保存至m1t.log文件 的當地語系化字串。
        /// </summary>
        public static string 终端内容已保存至m1t_log文件 {
            get {
                return ResourceManager.GetString("终端内容已保存至m1t_log文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設備串列埠： 的當地語系化字串。
        /// </summary>
        public static string 设备串口 {
            get {
                return ResourceManager.GetString("设备串口", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設備忙 的當地語系化字串。
        /// </summary>
        public static string 设备忙 {
            get {
                return ResourceManager.GetString("设备忙", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設置錯誤，請修改。 的當地語系化字串。
        /// </summary>
        public static string 设置错误_请修改 {
            get {
                return ResourceManager.GetString("设置错误_请修改", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 識別了以下設備： 的當地語系化字串。
        /// </summary>
        public static string 识别了以下设备 {
            get {
                return ResourceManager.GetString("识别了以下设备", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該扇區UID校驗值錯誤，已經自動為您更正。
        /// 的當地語系化字串。
        /// </summary>
        public static string 该扇区UID校验值错误_已经自动为您更正 {
            get {
                return ResourceManager.GetString("该扇区UID校验值错误_已经自动为您更正", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該扇區UID校驗值錯誤，已自動更正。
        /// 的當地語系化字串。
        /// </summary>
        public static string 该扇区UID校验值错误_已自动更正 {
            get {
                return ResourceManager.GetString("该扇区UID校验值错误_已自动更正", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該扇區UID校驗值錯誤，請點擊打開扇區0來自動更正。
        /// 的當地語系化字串。
        /// </summary>
        public static string 该扇区UID校验值错误_请点击打开扇区0来自动更正 {
            get {
                return ResourceManager.GetString("该扇区UID校验值错误_请点击打开扇区0来自动更正", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該扇區一切正常。
        /// 的當地語系化字串。
        /// </summary>
        public static string 该扇区一切正常 {
            get {
                return ResourceManager.GetString("该扇区一切正常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該扇區訪問控制位損壞，寫入將會損壞卡片，已重新設置。
        /// 的當地語系化字串。
        /// </summary>
        public static string 该扇区访问控制位损坏_写入将会损坏卡片_已重新设置 {
            get {
                return ResourceManager.GetString("该扇区访问控制位损坏_写入将会损坏卡片_已重新设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該扇區訪問控制位損壞，寫入將會損壞卡片，請重新設置。
        /// 的當地語系化字串。
        /// </summary>
        public static string 该扇区访问控制位损坏_写入将会损坏卡片_请重新设置 {
            get {
                return ResourceManager.GetString("该扇区访问控制位损坏_写入将会损坏卡片_请重新设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該扇區訪問控制位無效，寫入將會損壞卡片，已重新設置。
        /// 的當地語系化字串。
        /// </summary>
        public static string 该扇区访问控制位无效_写入将会损坏卡片_已重新设置 {
            get {
                return ResourceManager.GetString("该扇区访问控制位无效_写入将会损坏卡片_已重新设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該扇區訪問控制位無效，寫入將會損壞卡片，請重新設置。
        /// 的當地語系化字串。
        /// </summary>
        public static string 该扇区访问控制位无效_写入将会损坏卡片_请重新设置 {
            get {
                return ResourceManager.GetString("该扇区访问控制位无效_写入将会损坏卡片_请重新设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該操作將會清空UID卡內全部數據！！！
        ///清空後不可恢復！請確認是否要繼續操作？ 的當地語系化字串。
        /// </summary>
        public static string 该操作将会清空UID卡内全部数据_清空后不可恢复_请确认是否 {
            get {
                return ResourceManager.GetString("该操作将会清空UID卡内全部数据_清空后不可恢复_请确认是否", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該操作將會鎖死UFUID卡片！！！
        ///鎖死後不可恢復！無法再次更改0塊！請確認是否要繼續操作？ 的當地語系化字串。
        /// </summary>
        public static string 该操作将会锁死UFUID卡片_锁死后不可恢复_无法再次更改0 {
            get {
                return ResourceManager.GetString("该操作将会锁死UFUID卡片_锁死后不可恢复_无法再次更改0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該文件一切正常。 的當地語系化字串。
        /// </summary>
        public static string 该文件一切正常 {
            get {
                return ResourceManager.GetString("该文件一切正常", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該文件存在以下錯誤：
        /// 的當地語系化字串。
        /// </summary>
        public static string 该文件存在以下错误 {
            get {
                return ResourceManager.GetString("该文件存在以下错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請檢查接線是否正確/驅動是否正常安裝/設備電源是否已經打開（對於具有電源開關的型號）。 的當地語系化字串。
        /// </summary>
        public static string 请检查接线是否正确_驱动是否正常安装_设备电源是否已经打开_ {
            get {
                return ResourceManager.GetString("请检查接线是否正确_驱动是否正常安装_设备电源是否已经打开_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入UID號 的當地語系化字串。
        /// </summary>
        public static string 请输入UID号 {
            get {
                return ResourceManager.GetString("请输入UID号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入已知Key 的當地語系化字串。
        /// </summary>
        public static string 请输入已知Key {
            get {
                return ResourceManager.GetString("请输入已知Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入已知的Key，以英文半形逗號分隔。 的當地語系化字串。
        /// </summary>
        public static string 请输入已知的Key_以英文半角逗号分隔 {
            get {
                return ResourceManager.GetString("请输入已知的Key_以英文半角逗号分隔", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入需要寫入的UID卡號，共8位十六進位制數，如E44A3BF1。 的當地語系化字串。
        /// </summary>
        public static string 请输入需要写入的UID卡号_共8位十六进制数_如E44A3B {
            get {
                return ResourceManager.GetString("请输入需要写入的UID卡号_共8位十六进制数_如E44A3B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入需要更改的UID卡號，共8位十六進位制數，如E44A3BF1。 的當地語系化字串。
        /// </summary>
        public static string 请输入需要更改的UID卡号_共8位十六进制数_如E44A3B {
            get {
                return ResourceManager.GetString("请输入需要更改的UID卡号_共8位十六进制数_如E44A3B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇MCT.txt文件保存位置及檔案名 的當地語系化字串。
        /// </summary>
        public static string 请选择MCT_txt文件保存位置及文件名 {
            get {
                return ResourceManager.GetString("请选择MCT_txt文件保存位置及文件名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇MFD文件保存位置及檔案名 的當地語系化字串。
        /// </summary>
        public static string 请选择MFD文件保存位置及文件名 {
            get {
                return ResourceManager.GetString("请选择MFD文件保存位置及文件名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇一個包含目標卡金鑰的MFD文件（通常是已經破解出的該卡的MFD檔案） 的當地語系化字串。
        /// </summary>
        public static string 请选择一个包含目标卡密钥的MFD文件_通常是已经破解出的该卡 {
            get {
                return ResourceManager.GetString("请选择一个包含目标卡密钥的MFD文件_通常是已经破解出的该卡", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇金鑰字典文件保存位置及檔案名 的當地語系化字串。
        /// </summary>
        public static string 请选择密钥字典文件保存位置及文件名 {
            get {
                return ResourceManager.GetString("请选择密钥字典文件保存位置及文件名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇最後一次寫卡導致0塊損壞的卡數據文件 的當地語系化字串。
        /// </summary>
        public static string 请选择最后一次写卡导致0块损坏的卡数据文件 {
            get {
                return ResourceManager.GetString("请选择最后一次写卡导致0块损坏的卡数据文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇需要寫入的MFD文件 的當地語系化字串。
        /// </summary>
        public static string 请选择需要写入的MFD文件 {
            get {
                return ResourceManager.GetString("请选择需要写入的MFD文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇需要打開的MCT格式文件 的當地語系化字串。
        /// </summary>
        public static string 请选择需要打开的MCT格式文件 {
            get {
                return ResourceManager.GetString("请选择需要打开的MCT格式文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇需要打開的MFD文件 的當地語系化字串。
        /// </summary>
        public static string 请选择需要打开的MFD文件 {
            get {
                return ResourceManager.GetString("请选择需要打开的MFD文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇需要打開的MFD文件(比較A) 的當地語系化字串。
        /// </summary>
        public static string 请选择需要打开的MFD文件_比较A {
            get {
                return ResourceManager.GetString("请选择需要打开的MFD文件_比较A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇需要打開的MFD文件(比較B) 的當地語系化字串。
        /// </summary>
        public static string 请选择需要打开的MFD文件_比较B {
            get {
                return ResourceManager.GetString("请选择需要打开的MFD文件_比较B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇需要打開的金鑰字典文件 的當地語系化字串。
        /// </summary>
        public static string 请选择需要打开的密钥字典文件 {
            get {
                return ResourceManager.GetString("请选择需要打开的密钥字典文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 輸入的UID號不合法 的當地語系化字串。
        /// </summary>
        public static string 输入的UID号不合法 {
            get {
                return ResourceManager.GetString("输入的UID号不合法", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 運行中 的當地語系化字串。
        /// </summary>
        public static string 运行中 {
            get {
                return ResourceManager.GetString("运行中", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 運行時間: 的當地語系化字串。
        /// </summary>
        public static string 运行时间 {
            get {
                return ResourceManager.GetString("运行时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選擇key.mfd 的當地語系化字串。
        /// </summary>
        public static string 选择key_mfd {
            get {
                return ResourceManager.GetString("选择key_mfd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 錯誤 的當地語系化字串。
        /// </summary>
        public static string 错误 {
            get {
                return ResourceManager.GetString("错误", resourceCulture);
            }
        }
    }
}
